<?php require ("template/header.phtml")?>
    <!--<link href='http://fonts.googleapis.com/css?family=Bitter' rel='stylesheet' type='text/css'>-->
    <style type="text/css">

        .form-style-10{
            width:60%;
            padding:30px;
            margin:40px auto;
            background: #FFF;
            border-radius: 10px;
            -webkit-border-radius:10px;
            -moz-border-radius: 10px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.13);
            -moz-box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.13);
            -webkit-box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.13);
        }
        .form-style-10 .inner-wrap{
            padding: 30px;
            background: #85db23;
            border-radius: 6px;
            margin-bottom: 15px;
        }
        .form-style-10 h1
        {
            background: #85db23;
            padding: 20px 30px 15px 30px;
            margin: -30px -30px 30px -30px;
            border-radius: 10px 10px 0 0;
            -webkit-border-radius: 10px 10px 0 0;
            -moz-border-radius: 10px 10px 0 0;
            color: #fff;
            text-shadow: 1px 1px 3px rgba(0, 0, 0, 0.12);
            font: normal 30px 'Bitter', serif;
            -moz-box-shadow: inset 0px 2px 2px 0px rgba(255, 255, 255, 0.17);
            -webkit-box-shadow: inset 0px 2px 2px 0px rgba(255, 255, 255, 0.17);
            box-shadow: inset 0px 2px 2px 0px rgba(255, 255, 255, 0.17);
            border: 1px solid #257C9E;
        }
        .form-style-10 h1 > span
        {
            display: block;
            margin-top: 2px;
            font: 13px Arial, Helvetica, sans-serif;
        }
        .form-style-10 label
        {
            display: block;
            font: 20px Arial, Helvetica, sans-serif;
            color: #000000;
            margin-bottom: 15px;
        }
        .form-style-10 input[type="text"],
        .form-style-10 input[type="date"],
        .form-style-10 input[type="date"],
        .form-style-10 input[type="email"],
        .form-style-10 input[type="number"],
        .form-style-10 textarea,
        .form-style-10 select
        {
            display: block;
            box-sizing: border-box;
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
            width: 100%;
            padding: 8px;
            border-radius: 6px;
            -webkit-border-radius:6px;
            -moz-border-radius:6px;
            border: 2px solid #fff;
            box-shadow: inset 0px 1px 1px rgba(0, 0, 0, 0.33);
            -moz-box-shadow: inset 0px 1px 1px rgba(0, 0, 0, 0.33);
            -webkit-box-shadow: inset 0px 1px 1px rgba(0, 0, 0, 0.33);
        }

        .form-style-10 .section
        {
            font: normal 20px 'Bitter', serif;
            color: #000000;
            margin-bottom: 5px;
        }
        .form-style-10 .section span
        {
            background: #2a88ad;
            padding: 5px 10px 5px 10px;
            position: absolute;
            border-radius: 50%;
            -webkit-border-radius: 50%;
            -moz-border-radius: 50%;
            border: 4px solid #fff;
            font-size: 14px;
            margin-left: -45px;
            color: #fff;
            margin-top: -3px;
        }
        .form-style-10 input[type="button"],
        .form-style-10 input[type="submit"]
        {
            background: #2a88ad;
            padding: 8px 20px 8px 20px;
            border-radius: 5px;
            -webkit-border-radius: 5px;
            -moz-border-radius: 5px;
            color: #fff;
            text-shadow: 1px 1px 3px rgba(0, 0, 0, 0.12);
            font: normal 30px 'Bitter', serif;
            -moz-box-shadow: inset 0px 2px 2px 0px rgba(255, 255, 255, 0.17);
            -webkit-box-shadow: inset 0px 2px 2px 0px rgba(255, 255, 255, 0.17);
            box-shadow: inset 0px 2px 2px 0px rgba(255, 255, 255, 0.17);
            border: 1px solid #257c9e;
            font-size: 15px;
        }
        .form-style-10 input[type="button"]:hover,
        .form-style-10 input[type="submit"]:hover
        {
            background: #2a6881;
            -moz-box-shadow: inset 0px 2px 2px 0px rgba(255, 255, 255, 0.28);
            -webkit-box-shadow: inset 0px 2px 2px 0px rgba(255, 255, 255, 0.28);
            box-shadow: inset 0px 2px 2px 0px rgba(255, 255, 255, 0.28);
        }
        .form-style-10 .privacy-policy
        {
            float: right;
            width: 250px;
            font: 12px Arial, Helvetica, sans-serif;
            color: #4D4D4D;
            margin-top: 10px;
            text-align: right;
        }

        @media screen and (max-width: 800px) {
            .form-style-10 {
                width: 95%;
            }

            .form-style-10 label {
                font: 12px Arial, Helvetica, sans-serif;
            }
        }
    </style>

<section style="background: #C5E1A5">
    <br /> <br />
<div class="form-style-10">
    <h1>Upload Placement Details<span>Enter all the information related to the Placement Below!</span></h1>
    <form action="" method="post">
        <div>
            <p><?php if (isset($view->error)) {
                    echo $view->error;
                } ?></p>
        </div>

        <div class="section">Placement Title</div>
        <div class="inner-wrap">
            <label><input type="text" name="title" placeholder="Software Engineer placement ..."
                value="Student Software Engineer (12 month placement)"/></label>
        </div>

        <div class="section">Placement Description</div>
        <div class="inner-wrap">
            <label><textarea rows="4" cols="50" name="description" placeholder="200 character max ...">You'll join us on an initial 12-month placement and, after getting up to speed working on internal projects,you'll become part of an Agile development team; working in a fast-paced, customer-facing software development role.This will give you a great grounding in embedded software design, as well as commercial experience of C++and Java, and exposure to technologies such as Android.
                </textarea></label>
        </div>

        <div class="section">Benefits</div>
        <div class="inner-wrap">
            <label> <textarea rows="4" cols="50" name="benefits" >Be studying for an undergraduate honours degree in Computer Science, Computer Systems Engineering or a similar subject
Have completed at least two years of study by summer 2021
Have excellent communication skills in English (written and spoken)
Have excellent problem-solving skills
                </textarea></label>
        </div>

        <div class="section">Salary</div>
        <div class="inner-wrap">
            <label>e.g. 22000 <input type="text" name="salary" />
            <select name="salaryPaid">
                <option>Annually</option>
                <option>Monthly</option>
                <option>Weekly</option>
            </select></label>
        </div>

        <div class="section">Start Date</div>
        <div class="inner-wrap">
            <label> Start Date <input type="Date" name="startDate" /></label>
        </div>

        <div class="section">End Date</div>
        <div class="inner-wrap">
            <label> End Date <input type="Date" name="endDate" /></label>
        </div>

    <!--<form action="" method="post">
       <div class="section">Skills</div>
        <div class="inner-wrap">
            <input type="hidden" name="placementTitle" value="<?php /*if (isset($view->title)) {echo $view->title;}*/?>" />
            <label> Skill:
                <select name="skill">
                    <?php /*foreach ($view->allSkills as $skill) {
                        for ($i = $skill->getStartLevel(); $i < $skill->getEndLevel(); $i++) {
                            echo '<option>' . $skill->getSkill() . ' - Level ' . $i .
                                '</option>';
                        }
                    }*/?>
                </select>
                Level:
                <select name="skillLevel">
                    <?php /*/*for ($i = $view->getAllSkills->getStartLevel(); $i < $view->getAllSkills->getEndLevel(); $i++)
                        {
                            echo '<option>' . $i . '</option>';
                        }*/?>
                </select>
                <input type="submit" name="addSkill" value="add"/></label>
        </div>-->

        <div class="button-section">
            <input type="submit" name="createPlacement" value="Create" />
            <input type="submit" name="cancel" value="Cancel" />
            <!--<span class="privacy-policy">
     <input type="checkbox" name="field7">You agree to our Terms and Policy.
     </span>-->
        </div>
    </form>
</div>
<br /> <br />
</section>


<!--<div class="form-style-8">
    <h2>Enter Placement Details</h2>
    <form>
        <input type="text" name="Placement Description" placeholder="Placement Description" />
        <input type="email" name="Location" placeholder="Location" />
        <input type="text" name="Salary" placeholder="Salary" />
        <input type="Benefits" name="Benefits" placeholder="Benefits" />
        <input type="Date" name="Date" placeholder="Start and End Date" />
        <input type="text" name="Skills" placeholder="Required Skills" />
        <textarea placeholder="Message" onkeyup="adjust_textarea(this)"></textarea>
        <input type="button" value="Upload Placement Details" />
    </form>
</div>-->
<?php require ("template/footer.phtml")?>
