<?php require("template/header.phtml") ?>


    <header class="masthead text-center text-white">
        <div class="masthead-content">
            <div class="container">
                <h1 class="masthead-heading mb-0"><?php echo $view->pageTitle ?></h1>
                <h2 class="masthead-subheading mb-0">Placements</h2>
                <?php if (!isset($_SESSION['loggedIn'])) : ?>
                <a href="login.php" class="btn btn-primary btn-xl rounded-pill mt-5">Login</a>
                <a href="register.php" class="btn btn-primary btn-xl rounded-pill mt-5">Register</a>
                <?php endif; ?>
                <?php if (isset($_SESSION['typeOfUser']) && $_SESSION['typeOfUser'] == "Employer") : ?>
                    <a href="createPlacement.php" class="btn btn-primary btn-xl rounded-pill mt-5">Create Placement Offer</a>
                <?php endif; ?>
            </div>
        </div>
        <div class="bg-circle-1 bg-circle"></div>
        <div class="bg-circle-2 bg-circle"></div>
        <div class="bg-circle-3 bg-circle"></div>
        <div class="bg-circle-4 bg-circle"></div>
    </header>

    <section>
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6 order-lg-2">
                    <div class="p-5">
                        <img class="img-fluid rounded-circle" src="img/01.jpg" alt="">
                    </div>
                </div>
                <div class="col-lg-6 order-lg-1">
                    <div class="p-5">
                        <h2 class="display-4">Who are we?</h2>
                        <p>As a charity with a royal charter, our agenda is to lead the IT industry through its ethical challenges, to support the people who work in the industry, and to make IT good for society.
                            We are expanding our purpose by creating new job advertisement website that takes the stress and ease from you manually searching and applying for the
                            jobs, the way our site works is that when you register to our website you upload your CV with your details and what type of industry you're
                            looking to go to and then you sit back and relax because our algorithm sends your details to employers that are looking for recruitment, if
                            an employer is impressed with your CV you will be notified and then you can accept and decline the offer in the placement offers section.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section>
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6">
                    <div class="p-5">
                        <img class="img-fluid rounded-circle" src="img/employers.jpg" alt="">
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="p-5">
                        <h2 class="display-4">Employers</h2>
                        <p>For employers our website helps find your new employees so easily, All you need to is upload
                            your placement application, making sure you include the location, salary, benefits, start and end
                            time and required skills. Once you have inserted all them requirements, the algorithm will then
                            match students with the skills you added in the requirments.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section>
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6 order-lg-2">
                    <div class="p-5">
                        <img class="img-fluid rounded-circle" src="img/employees.jpg" alt="">
                    </div>
                </div>
                <div class="col-lg-6 order-lg-1">
                    <div class="p-5">
                        <h2 class="display-4">Students</h2>
                        <p>For Students we have made looking for an application very easy for you all you have to do to
                            access get is register, upload your CV and set your required skill. We have taken you privacy
                            into consideration, so until and employer send you an placement application, they will not be
                            able to view your CV, which will have your personal detail.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

 <?php require ("template/footer.phtml") ?>