<?php require ("template/header.phtml") ?>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        body
        {
            background: #C5E1A5;
        }
        form
        {
            width: 50%;
            margin: 60px auto;
            background: #2E8B57;
            padding: 60px 120px 80px 120px;
            text-align: center;
            -webkit-box-shadow: 2px 2px 3px rgba(0,0,0,0.1);
            box-shadow: 2px 2px 3px rgba(0,0,0,0.1);
        }

        label
        {
            display: block;
            position: relative;
            margin: 40px 0px;
        }

        .label-txt {

            position: absolute;
            top: -1.6em;
            padding: 10px;
            font-family: sans-serif;
            font-size: .8em;
            letter-spacing: 1px;
            color: rgb(120,120,120);
            transition: ease .3s;
        }
        .input
        {
            width: 100%;
            padding: 10px;
            background: transparent;
            border: none;
            outline: none;
        }

        .line-box
        {
            position: relative;
            width: 100%;
            height: 2px;
            background: #BCBCBC;
        }
        .line
        {
            position: absolute;
            width: 0%;
            height: 2px;
            top: 0px;
            left: 50%;
            transform: translateX(-50%);
            background: #8BC34A;
            transition: ease .6s;
        }
        .input:focus + .line-box .line
        {
            width: 100%;
        }
        .label-active
        {
            top: -3em;
        }

        input::placeholder {
            color: #000000;
        }

        button
        {
            display: inline-block;
            padding: 12px 24px;
            background: rgb(220,220,220);
            font-weight: bold;
            color: rgb(120,120,120);
            border: none;  outline: none;
            border-radius: 3px;
            cursor: pointer;
            transition: ease .3s;
        }
        button:hover
        {
            background: #8BC34A;
            color: #ffffff;
        }

        .reCaptcha {
            padding: 10px;
            width: 30%;
            background: #8BC34A;
            font-size: 30px;
            border: 3px solid #000000;
        }

        @media screen and (max-width: 800px) {
            input, .line, .form-group, input[type=submit] {
                width: 100%;
                margin-top: 0;
            }

            .reCaptcha {
                width: 100%;
            }
        }
    </style>

<br /><br /><br /><br />
<div>
<form action="" method="post" class="form-group">
    <h1 style="color:#000000;">Login</h1>
    <label>
        <input type="text" class="input" name="userEmail" placeholder="Email" value="student@edu.email.ac.uk"/>
        <div class="line-box">
            <div class="line"></div>
        </div>
    </label>

    <!--<label>
        <input
                type="text"
                class="input"
                name="username"
                placeholder="Username"/>
        <div class="line-box">
            <div class="line"></div>
        </div>
    </label>-->

    <label>
        <input
                type="password"
                class="input"
                name="pwd"
                placeholder="Password"
                value="123456789"/>
        <div class="line-box">
            <div class="line"></div>
        </div>
    </label>

    <div class="reCaptcha">
        <p><b><?php if (isset($view->finalReCaptcha)) {echo $view->finalReCaptcha;} ?></b></p>
    </div>

    <label>
        <input
                type="text"
                class="input"
                name="reCaptcha"
                placeholder=""
                value=""/>
        <div class="line-box">
            <div class="line"></div>
        </div>
    </label>

    <input type="submit" name="login" value="Login" class="btn btn-dark">
    <p style="color: #bd2130;"><?php if (isset($view->error)) {echo $view->error;}?></p>
</form>
</div>
<br /><br /><br /><br /><br /><br /><br /><br />

<?php require ("template/footer.phtml") ?>