<?php require ("template/header.phtml") ?>

<style>
    #placementSection {
        border-bottom: 5px solid #000000;
    }

    .myPlacementSection {
        margin-top: 100px;
        margin-bottom: 150px;
    }
</style>

<br /> <br />
<section class="myPlacementSection">
    <div class="container">
        <div class="row">
            <h1><?php $view->pageTitle ?></h1>
        </div>
        <div class="row">
            <?php foreach ($view->allPlacements as $placement) {
                echo '<form action="" method="post">' .
                    '<div class="row" id="placementSection"><h4>#' . $placement->getPlacementID() .
                    '. ' . $placement->getTitle() . ' - ' . $placement->getSector() . '</h4></div>' .
                    '<input type="hidden" name="placement_id" value="' . $placement->getPlacementID() . '"/>' . '<br />' .
                    '<h6>Company: ' . $placement->getCompany() . '</h6>' . '<br />' . '<h6>Description</h6>' .
                    '<div class="row">' . $placement->getDescription() . '</div>' . '<br />' .
                    '<h6>Benefits</h6>' .
                    '<div class="row">' . $placement->getBenefits() . '</div><br />' .
                    '<div class="row"><div class="col-sm-12"><h6>Location: </h6></div><div class="col-sm-1">' . $placement->getLocation() .
                    '</div></div>' . '<br />' . '<div class="row"><p><b>Salary:</b>  £' . $placement->getSalary() .
                    ' ' . $placement->getSalaryPaid() . '</p></div>' .
                    '<div class="row"><div class="col-sm-2"><p><b>Start Date:</b>' . $placement->getStartDate() .
                    '</p></div><div class="col-sm-2"><p><b>End Date:</b> ' . $placement->getEndDate() . '</p></div></div>';

                echo '<div class="row"><div class="cols-sm-3"><p><b>Add required skills for placement
                        </b></p></div><div class="col-sm-2">';
                echo '<select name="skill">';

                foreach ($view->allSkills as $skill)
                {
                    for ($i = $skill->getStartLevel(); $i < $skill->getEndLevel() + 1; $i++)
                    {
                        echo '<option>' . $skill->getSkillID() .
                            '. ' . $skill->getSkill() . ' - level ' . $i . '</option>';
                    }
                }
                echo '</select>';
                echo '<input type="submit" name="addSkill" value="Add Skill" class="btn btn-dark"></div></div>
                        <div class="row"><input type="hidden" name="pageTrack" value="' . $_SESSION['page'] .'" class="btn btn-dark">
                        <input type="submit" name="showSkills" value="Show Required Skills" class="btn btn-dark"></div><br />';

                    if (isset($_POST['showSkills']))
                    {
                        echo '<br /><div class="row"><h6>Required Skills: </h6>';
                        if ($view->allPlacementSkills) {
                            foreach ($view->allPlacementSkills as $placementSkill) {
                                echo '<div class="col-sm-2">';
                                echo '<form action="" method="post"><p><b>' . $placementSkill->getSkill() .
                                    ' - Level ' . $placementSkill->getLevel() . '</b></p></form>';
                                echo '</div>';
                            }
                        }
                        echo '</div></form>';
                    }
            }?>

            <form action="" method="post"><input type="submit" name="prePage" value="Back" class="btn btn-dark">
                <input type="submit" name="nextPage" value="Next" class="btn btn-dark"></form>
        </div>

    </div>
</section>

<?php require ("template/footer.phtml") ?>
