<?php require ("template/header.phtml") ?>
    <style>
        body
        {
            background: #C5E1A5;
        }
        form
        {
            width: 30%;
            margin: 60px auto;
            background: #efefef;
            padding: 60px 120px 80px 120px;
            text-align: center;
            -webkit-box-shadow: 2px 2px 3px rgba(0,0,0,0.1);
            box-shadow: 2px 2px 3px rgba(0,0,0,0.1);
        }

        label
        {
            display: block;
            position: relative;
            margin: 40px 0px;
        }

        .label-txt {

            position: absolute;
            top: -1.6em;
            padding: 10px;
            font-family: sans-serif;
            font-size: .8em;
            letter-spacing: 1px;
            color: rgb(120,120,120);
            transition: ease .3s;
        }
        .input
        {
            width: 100%;
            padding: 10px;
            background: transparent;
            border: none;
            outline: none;
        }

        .line-box
        {
            position: relative;
            width: 100%;
            height: 2px;
            background: #BCBCBC;
        }
        .line
        {
            position: absolute;
            width: 0%;
            height: 2px;
            top: 0px;
            left: 50%;
            transform: translateX(-50%);
            background: #8BC34A;
            transition: ease .6s;
        }
        .input:focus + .line-box .line
        {
            width: 100%;
        }
        .label-active
        {
            top: -3em;
        }
        button
        {
            display: inline-block;
            padding: 12px 24px;
            background: rgb(220,220,220);
            font-weight: bold;
            color: rgb(120,120,120);
            border: none;  outline: none;
            border-radius: 3px;
            cursor: pointer;
            transition: ease .3s;
        }
        button:hover
        {
            background: #8BC34A;
            color: #ffffff;
        }
    </style>
</head>
<body>
<section>
    <div>
        <form action="" method="post" class="form-group">
            <h4 class="text-warning text-center pt-5">Registration Page</h4>
            <select name="userType">
                <option>Student</option>
                <option>Employer</option>
            </select>
<!--            <input type="text" name="newFullName" value="Legend Expression" >-->
            <!--<input type="text" name="email" value="legend.expression@edu.salford.ac.uk" >
            <input type="password" name="newPwd" value="123456789" >
            <input type="text" name="phone_number" value="0712345678" >
            <input type="text" name="address" value="51 princess road, M16">
            <input type="submit" name="register" value="Sign Up" >-->
                    <label>
                        <input
                                type="text"
                                class="input"
                                name="newFullName"
                                placeholder="Full Name"
                                value="student"/>
                        <div class="line-box">
                            <div class="line"></div>
                        </div>
                    </label>

                    <label>
                        <input type="text" class="input" name="email" placeholder="Email" value="student@edu.email.ac.uk"/>
                        <div class="line-box">
                            <div class="line"></div>
                        </div>
                    </label>

                    <!--<label>
                        <input
                                type="text"
                                class="input"
                                name="username"
                                placeholder="Username"/>
                        <div class="line-box">
                            <div class="line"></div>
                        </div>
                    </label>-->

                    <label>
                        <input
                                type="password"
                                class="input"
                                name="newPwd"
                                placeholder="Password"
                                value="123456789"/>
                        <div class="line-box">
                            <div class="line"></div>
                        </div>
                    </label>
                    <label>
                        <input
                                type="password"
                                class="input"
                                name="confirmPassword"
                                placeholder="Confirm Password"
                                value="123456789"/>
                        <div class="line-box">
                            <div class="line"></div>
                        </div>
                    </label>

                    <label>
                        <input
                                type="text"
                                class="input"
                                name="phone_number"
                                placeholder="Contact Number"
                                value="1234567890"/>
                        <div class="line-box">
                            <div class="line"></div>
                        </div>
                    </label>

                    <label>
                        <input
                                type="text"
                                class="input"
                                name="address"
                                placeholder="Address"
                                value="12 Street, Manchester, M18"/>
                        <div class="line-box">
                            <div class="line"></div>
                        </div>
                    </label>

                    <input type="submit" name="register" value="Register">
            <p style="color: #bd2130"><?php echo $view->error ?></p>
            </div>
        </form>
    </div>
</section>

<?php require ("template/footer.phtml") ?>
