<?php require ("template/header.phtml")?>

<section>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 order-lg-2">
                <div class="p-5">
                    <img class="img-fluid rounded-circle" src="img/01.jpg" alt="">
                </div>
            </div>
            <div class="col-lg-6 order-lg-1">
                <div class="p-5">
                    <h2 class="display-4">Who are we?</h2>
                    <p>As a charity with a royal charter, our agenda is to lead the IT industry through its ethical challenges, to support the people who work in the industry, and to make IT good for society.
                        We are expanding our purpose by creating new job advertisement website that takes the stress and ease from you manually searching and applying for the
                        jobs, the way our site works is that when you register to our website you upload your CV with your details and what type of industry you're
                        looking to go to and then you sit back and relax because our algorithm sends your details to employers that are looking for recruitment, if
                        an employer is impressed with your CV you will be notified and then you can accept and decline the offer in the placement offers section.</p>
                </div>
            </div>
        </div>
    </div>
    <form action="" method="post" enctype="multipart/form-data">
        <p><?php if (isset($view->error)) {echo $view->error;} ?></p>
        Select file to upload:
        <input type="file" name="fileToUpload" id="fileToUpload">
        <input type="submit" value="Upload" name="cvUpload">
    </form>
</section>

<?php require ("template/footer.phtml")?>