<?php require ("template/header.phtml")?>
    <style type="text/css">

        section {
            background: #8BC34A;
        }

        .form-style-10
        {
            width:70%;
            padding:30px;
            margin:auto;
            background: #FFF;
            border-radius: 10px;
            -webkit-border-radius:10px;
            -moz-border-radius: 10px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.13);
            -moz-box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.13);
            -webkit-box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.13);
        }
        .form-style-10 .inner-wrap
        {
            padding: 30px;
            background: #85db23;
            border-radius: 6px;
            margin-bottom: 15px;
        }
        .form-style-10 h1
        {
            background: #85db23;
            padding: 20px 30px 15px 30px;
            margin: -30px -30px 30px -30px;
            border-radius: 10px 10px 0 0;
            -webkit-border-radius: 10px 10px 0 0;
            -moz-border-radius: 10px 10px 0 0;
            color: #fff;
            text-shadow: 1px 1px 3px rgba(0, 0, 0, 0.12);
            font: normal 30px 'Bitter', serif;
            -moz-box-shadow: inset 0px 2px 2px 0px rgba(255, 255, 255, 0.17);
            -webkit-box-shadow: inset 0px 2px 2px 0px rgba(255, 255, 255, 0.17);
            box-shadow: inset 0px 2px 2px 0px rgba(255, 255, 255, 0.17);
            border: 1px solid #257C9E;
        }
        .form-style-10 h1 > span
        {
            display: block;
            margin-top: 2px;
            font: 13px Arial, Helvetica, sans-serif;
        }
        .form-style-10 label
        {
            display: block;
            font: 13px Arial, Helvetica, sans-serif;
            color: #000000;
            margin-bottom: 15px;
        }
        .form-style-10 input[type="text"],
        .form-style-10 input[type="date"],
        .form-style-10 input[type="date"],
        .form-style-10 input[type="email"],
        .form-style-10 input[type="number"],
        .form-style-10 textarea,
        .form-style-10 select
        {
            display: block;
            box-sizing: border-box;
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
            width: 100%;
            padding: 8px;
            border-radius: 6px;
            -webkit-border-radius:6px;
            -moz-border-radius:6px;
            border: 2px solid #fff;
            box-shadow: inset 0px 1px 1px rgba(0, 0, 0, 0.33);
            -moz-box-shadow: inset 0px 1px 1px rgba(0, 0, 0, 0.33);
            -webkit-box-shadow: inset 0px 1px 1px rgba(0, 0, 0, 0.33);
        }

        .form-style-10 .section
        {
            font: normal 20px 'Bitter', serif;
            color: #000000;
            margin-bottom: 5px;
        }
        .form-style-10 .section span
        {
            background: #2a88ad;
            padding: 5px 10px 5px 10px;
            position: absolute;
            border-radius: 50%;
            -webkit-border-radius: 50%;
            -moz-border-radius: 50%;
            border: 4px solid #fff;
            font-size: 14px;
            margin-left: -45px;
            color: #fff;
            margin-top: -3px;
        }
        .form-style-10 input[type="button"],
        .form-style-10 input[type="submit"]
        {
            padding: 8px 20px 8px 20px;
            border-radius: 5px;
            -webkit-border-radius: 5px;
            -moz-border-radius: 5px;
            color: #ffffff;
            text-shadow: 1px 1px 3px rgba(0, 0, 0, 0.12);
            font: normal 30px 'Bitter', serif;
            -moz-box-shadow: inset 0px 2px 2px 0px rgba(255, 255, 255, 0.17);
            -webkit-box-shadow: inset 0px 2px 2px 0px rgba(255, 255, 255, 0.17);
            box-shadow: inset 0px 2px 2px 0px rgba(255, 255, 255, 0.17);
            border: 1px solid #257c9e;
            font-size: 15px;
        }
        .form-style-10 input[type="button"]:hover,
        .form-style-10 input[type="submit"]:hover
        {
            background: #2a6881;
            -moz-box-shadow: inset 0px 2px 2px 0px rgba(255, 255, 255, 0.28);
            -webkit-box-shadow: inset 0px 2px 2px 0px rgba(255, 255, 255, 0.28);
            box-shadow: inset 0px 2px 2px 0px rgba(255, 255, 255, 0.28);
        }
        .form-style-10 .privacy-policy
        {
            float: right;
            width: 250px;
            font: 12px Arial, Helvetica, sans-serif;
            color: #4D4D4D;
            margin-top: 10px;
            text-align: right;
        }

        #studentSkills {
            overflow: scroll;
            padding: 2px 2px 2px 20px;
            min-width: 60%;
            width: 80%;
            border: 2px solid #000000;
        }

        @media screen and (max-width: 800px) {
            .form-style-10 {
                width: 100%;
            }

            .skillMenu option {
                width: 40%;
            }

            #studentSkills {
                width: 40%;
            }
        }
    </style>

    <section>
        <br /><br /><br /><br /><br /><br /><br />
        <div class="container" id="profileSection">
            <div class="form-style-10">
                <h1><?php echo $_SESSION['username'];?></h1>
                <div class="container">
                    <div class="row">
                        <div class="well profile">
                            <div>
                                <form action="" method="post">
                        <h4>Your Details</h4>
                        <p><b>Email:</b> <?php if (isset($_SESSION['email'])) {echo $_SESSION['email'];} ?></p>
                        <p><b>Phone Number:</b> <?php if (isset($_SESSION['phone'])) {echo $_SESSION['phone'];}?></p>
                                    <?php if (isset($_SESSION['changeStudentDetails'])) : ?>
                                    <input type="text" name="updatePhoneNumber" placeholder="Type your new phone number ..."/>
                                    <?php endif; ?>
                        <p><b>Address:</b> <?php if (isset($_SESSION['address'])) {echo $_SESSION['address'];}?></p>
                                    <?php if (isset($_SESSION['changeStudentDetails'])) : ?>
                                    <input type="text" name="updateAddress" placeholder="Type your new address ..."/>
                                    <?php endif; ?>
                        <div>
                                <div class="row">
                                    <div>
                                        <?php if (!isset($_SESSION['changeStudentDetails'])) : ?>
                                        <input type="submit" name="changeDetails" value="Change Details" class="btn btn-dark"/>
                                        <?php endif; ?>
                                        <?php if (isset($_SESSION['changeStudentDetails'])) : ?>
                                        <input type="submit" name="updateDetails" value="Update" class="btn btn-dark"/>
                                        <?php endif; ?>
                                    </div>
                                </form>
                                </div>
                            <br />
                            <div class="row">
                                <form action="" method="post">
                                    <div>
                                        <p><?php if (isset($view->showSector)) {
                                            echo '<b>Your Sector: </b>' . $view->showSector;
                                        }
                                        else
                                        {
                                            echo 'Please add your sector';
                                        }?></p>
                                    </div>
                                    <div>
                                        <select name="studentSector">
                                            <option>Information Technology</option>
                                            <option>Business</option>
                                            <option>Engineering</option>
                                            <option>Medical and Healthcare</option>
                                            <option>Creative arts and design</option>
                                            <option>Energy and utilities</option>
                                            <option>Energy and utilities</option>
                                        </select>
                                        <br />
                                        <input type="submit" name="addSector" value="Add Sector" class="btn btn-dark"/>
                                    </div>
                                </form>
                            </div>
                            <br />
                                <div class="row" id="studentSkills">
                                    <p><b>Skills</b></p>
                                    <ul>
                                    <?php if (!$view->listSkills)
                                    {
                                        echo '<p>Add your skills here ...</p>';
                                    }
                                    else
                                    {
                                        foreach ($view->listSkills as $studentSkill)
                                        {
                                            echo '<div class="col-sm-12"><form action="" method="post"><li>' .
                                                $studentSkill->getSkill() . ' - Level ' . $studentSkill->getLevel() .
                                                '<input type="hidden" name="skill_id" value="' . $studentSkill->getSkillID() . '"/>'
                                                . '</li><input type="submit" name="removeSkill" value="X" class="btn btn-danger" /></form></div>';
                                        }
                                    }?>
                                    </ul>
                                </div>

                                <div class="row">
                                <form action="" method="post">
                                    <br />
                                    <select name="studentSkill" class="skillMenu">
                                        <?php foreach ($view->showSkills as $skill)
                                            {
                                                for ($i = $skill->getStartLevel(); $i < ($skill->getEndLevel() + 1); $i++)
                                                {
                                                    echo '<option>' . $skill->getSkillID() . '. ' .
                                                        $skill->getSkill() . ' - Level ' .  $i . '</option>';
                                                }
                                            }?>
                                        <div>
                                            <input type="submit" name="addStudentSkills" value="Add Skills" class="btn btn-dark" />
                                        </div>
                                    </select>
                                </form>
                                </div>
                        </div>

                        <form action="" method="post" enctype="multipart/form-data">
                            <p style="color: #bd2130;"><?php if (isset($view->error)) {echo $view->error;} ?></p>
                            Select file to upload:
                            <input type="file" name="fileToUpload" id="fileToUpload">
                            <input type="submit" value="Upload" name="cvUpload" class="btn btn-dark">
                        </form>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <br /><br /><br /><br /><br /><br /><br /><br /><br />
        </div>
    </section>

<?php require ("template/footer.phtml")?>