<?php require ("template/header.phtml") ?>

<style>
    #placementHolder {
        margin-top: 100px;
    }

    #placementSection {
        border-bottom: 5px solid #000000;
    }

    @media screen and (max-width: 800px) {
        #placementHolder {
            padding: 10px;
            width: 100%;
        }
    }
</style>

<section>
    <div class="container" id="placementHolder">
    <div class="row">
        <?php foreach ($view->allPlacements as $placement) {
            echo '<form action="" method="post">' .
                '<div class="row" id="placementSection"><h4>' .
                $placement->getTitle() . ' - ' . $placement->getCompany() . '</h4></div>' .
                '<input type="hidden" name="placement_id" value="' . $placement->getPlacementID() . '"/>' . '<br />' .
                '<h6>Description</h6>' .
                '<div class="row">' . $placement->getDescription() . '</div>' . '<br />' .
                '<h6>Benefits</h6>' .
                '<div class="row">' . $placement->getBenefits() . '</div><br />' .
                '<div class="row"><p><b>Salary:</b>  £' . $placement->getSalary() .
                ' ' . $placement->getSalaryPaid() . '</p></div>' .
                '<div class="row"><div class="col-sm-2"><p><b>Start Date:</b>' . $placement->getStartDate() .
                '</p></div><div class="col-sm-2"><p><b>End Date:</b> ' . $placement->getEndDate() . '</p></div></div>';

        }?>
    </div>
        <div class="">
            <form action="" method="post"><input type="submit" name="prePage" value="Back" class="btn btn-dark">
            <input type="submit" name="nextPage" value="Next" class="btn btn-dark"></form>
        </div>
    </div>
    </div>
    <br />
</section>

<?php require ("template/footer.phtml") ?>