<?php require ('template/header.phtml') ?>

<style>
    .messageBox
    {
        padding: 10px 40px;
        border: 5px solid #000000;
        font-size: 20px;
    }

    #message
    {
        padding: 10px 20px;
        background: linear-gradient(#71982c, #c9ff69);
        border-bottom: 5px solid #000000;
    }
</style>

<section style="margin-bottom: 100px">
    <div class="container-fluid" style="margin-top: 100px;">
        <div class="row">
            <div>
                <h1><?php echo $view->pageTitle ?></h1>
            </div>
        </div>
        <div class="messageBox">
            <?php if (!$view->allMessages)
                {
                    echo $view->error;
                }
                else
            {
                foreach ($view->allMessages as $message)
                {
                    echo '<div class="row" id="message"><form action="" method="post"><b>#0' . $message->getMessageID() .
                        '<input type="hidden" name="messageID" value="' . $message->getMessageID() . '" />' .
                        '0</b> ----- ' . $message->getMessage() . '<input type="submit" name="removeMessage" value="X" class="btn btn-danger"/>
                        </form></div><br />';
                }
            }?>
        </div>
    </div>
</section>

<?php require ('template/footer.phtml') ?>
