</div>
<!-- Footer -->
<footer class="py-5 bg-black">
    <div class="container">
        <div class="d-flex justify-content-center" style="border-bottom: 3px solid #FFFFFF;">
            <div>
                <a href="https://www.facebook.com/IT.BCS/" target="_blank"><img src="img/facebook_logo.png" alt="FaceBook" /></a>
            </div>
            <div>
                <a href="https://twitter.com/bcs?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor" target="_blank"><img src="img/Twitter_logo.png" alt="Twitter" /></a>
            </div>
            <div>
                <a href="https://www.youtube.com/channel/UCbOuaNSjnye_DHcw8411hxg" target="_blank"><img src="img/youtube_logo.png" alt="YouTube" /></a>
            </div>
        </div>
        <br />
        <p class="m-0 text-center text-white small">Copyright &copy; Group 16</p>
    </div>
    <!-- /.container -->
</footer>

<!-- Bootstrap core JavaScript -->
<script src="../../vendor/jquery/jquery.min.js"></script>
<script src="../../vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>