<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>BCS Placements</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/one-page-wonder.css" rel="stylesheet">

</head>

<body>
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
    <!--<div style="position: absolute; top: 70px">
        <a href="index.php"><img src="img/BCSLogo.png" alt="BCS logo" /></a>
    </div>-->
    <div class="container">
        <!--<a class="navbar-brand" href="#">Start Bootstrap</a>-->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <!--<li class="nav-item">
                    <a class="nav-link" href="#">Sign Up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Log In</a>
                </li>-->
                <li class="nav-item">
                    <a class="nav-link" href="index.php">Home</a>
                </li>
                <?php if (isset($_SESSION['loggedIn']))  : ?>
                <?php if (isset($_SESSION['typeOfUser']) && $_SESSION['typeOfUser'] == "Student")  : ?>
                    <li class="nav-item">
                        <a class="nav-link" href="studentProfile.php">My Profile</a>
                    </li>
                <?php endif; ?>
                    <?php if (isset($_SESSION['typeOfUser']) && $_SESSION['typeOfUser'] == "Employer")  : ?>
                        <li class="nav-item">
                            <a class="nav-link" href="myPlacements.php">My Placements</a>
                        </li>
                    <?php endif; ?>
                <form action="" method="post">
                    <?php if (isset($_SESSION['username'])) :?>
                    <?php echo 'Hello, ' . $_SESSION['username']?>
                    <?php endif; ?>
                    <input type="submit" name="logout" value="Logout" class="btn btn-danger">
                </form>
                <?php endif; ?>
            </ul>
        </div>
    </div>
</nav>

<div class="container-fluid">